[package]
name = "metis-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "metis-cli"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
metis-compute = { path = "../metis-compute" }
metis-core = { path = "../metis-core" }
metis-db = { path = "../metis-db" }

[lints]
workspace = true
